<?php

$options = [
    ""=>"-- Please select --",
    "AUD" => "AUD",
    "BRL" => "BRL",
    "CAD" => "CAD",
    "CHF" => "CHF",
    "DKK" => "DKK",
    "DCO" => "DCO",
    "EUR" => "EUR",
    "GBP" => "GBP",
    "HKD" => "HKD",
    "JPY" => "JPY",
    "MXN" => "MXN",
    "NOK" => "NOK",
    "NZD" => "NZD",
    "PLN" => "PLN",
    "RUB" => "RUB",
    "SEK" => "SEK",
    "SGD" => "SGD",
    "TRY" => "TRY",
    "USD" => "USD",
    "ZAR" => "ZAR",
    "BTC" => "BTC",
];

require 'select.phtml';