<?php 
/** 
 * @var string $type
 * @var string $name
 * @var string $class
 * @var string $value
 * @var bool $disabled
 * @var bool $checked
 * @var string $placeholder
 */

$type = !empty($type) ? $type : 'text';
$class = !empty($class) ? $class : '';
$disabled = isset($disabled) && boolval($disabled) ? 'disabled' : '';
$value = isset($value) ? $value : '';
$checked = isset($checked) && boolval($checked) ? 'checked' : '';
$placeholder = !empty($placeholder) ? "placeholder=\"{$placeholder}\"" : '';
?>
<input id="<?= $name; ?>" 
       name="<?= $name; ?>" 
       class="form-control <?= $class; ?>"
       type="<?= $type; ?>"
       value="<?= $value; ?>" <?= $disabled; ?> <?= $checked; ?> <?= $placeholder; ?> />