<!DOCTYPE HTML>
<html>
<head>
    <title>Workflow API Tester</title>

    <link href="api.ico" rel="icon">

    <link href="media/css/bootstrap.min.css" rel="stylesheet">
    <link href="media/css/common.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse"
                    class="navbar-toggle collapsed" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Workflow API Tester</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
